[package]
authors = ["Sho Nakatani <lay.sakura@gmail.com>"]
license = "TBD"
name = "springql-client-c"
version = "0.1.0"

edition = "2021"

[build-dependencies]
cbindgen = "0.20"

[dependencies]
springql-core = {path = "../SpringQL/SpringQL-core"}
