name: create-release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get version from Cargo.toml
        id: crate-version
        run: |
          crate_version="$(cargo metadata --format-version=1 |jq '.packages[] | select(.name == "springql-client-c")' |jq -r '.version')"
          echo "crate version: $crate_version"
          echo "::set-output name=version::v${crate_version}"

      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
          CRATE_VERSION: ${{ steps.crate-version.outputs.version }}
