name: create-release

on:
  pull_request:
    types:
      - opened
      - synchronize

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    outputs:
      crate-version: ${{ steps.crate-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Get version from Cargo.toml
        id: crate-version
        run: |
          echo "::set-output name=version::v$(cargo metadata --format-version=1 |jq '.packages[] | select(.name == "springql-client-c")' |jq -r '.version')"

      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: release
          CRATE_VERSION: ${{ steps.crate-version.outputs.version }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
